export enum AdminRoutes {
  LoginPage = '/admin',
  MainPage = '/admin/main-page',
  AboutUsPage = '/admin/about-us',
  OurTeamPage = '/admin/our-team',
  CasesPage = '/admin/cases',
  ServicesPage = '/admin/services-main',
  ServicePackages = '/admin/services-packages',
  ServicesButtonPage = '/admin/services-button',
  ServicesListPage = '/admin/services-list',
  CareerPage = '/admin/career',
  GoTherePage = '/admin/go-there',
  Footer = '/admin/footer',
  SocialNetworks = '/admin/social-networks',
  CVRequests = '/admin/cv/requests',
  ConsultationRequests = '/admin/go-there/requests',
}
